repos:

- repo: https://github.com/PyCQA/isort
  rev: 5.5.4
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
    args: [--remove]
  - id: forbid-new-submodules
  - id: mixed-line-ending
    args: [--fix=lf]
# Cannot use for now due to our factories.py files
#  - id: name-tests-test
#    args: [--django]
  - id: no-commit-to-branch
    args: [--branch=master]
  - id: trailing-whitespace
