version: 2.1
#orbs:
#  codecov: codecov/codecov@1.0.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10
      - image: cimg/redis:6.2
    steps:
      - checkout
      - run: make install-poetry
      - run: make test
      #- codecov/upload:
      #    file: htmlcov/
