name: "Continuous Integration"
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: pre-commit
      uses: pre-commit/action@v2.0.3

  test:
    # needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: false

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install tox
      shell: bash
      run: |
        pip install tox

    - name: tox tests
      run: tox
